import { NextResponse } from "next/server";

// Gyms in Visakhapatnam with real area names and approximate coordinates (lat, lng).
// Distance is computed client-side from user location when available.
const gyms = [
  {
    id: 0,
    name: "FitZone RK Beach",
    address: "RK Beach Road, Visakhapatnam",
    lat: 17.7292,
    lng: 83.321,
    rating: "4.8",
    hourlyPrice: 99,
    weeklyPrice: 599,
    monthlyPrice: 1999,
    featured: true,
  },
  {
    id: 1,
    name: "Power House Gym Jagadamba",
    address: "Jagadamba Junction, Visakhapatnam",
    lat: 17.7216,
    lng: 83.3022,
    rating: "4.5",
    hourlyPrice: 79,
    weeklyPrice: 499,
    monthlyPrice: 1699,
    featured: false,
  },
  {
    id: 2,
    name: "Fitness First MVP Colony",
    address: "MVP Colony, Sector 6, Visakhapatnam",
    lat: 17.735,
    lng: 83.308,
    rating: "4.7",
    hourlyPrice: 119,
    weeklyPrice: 699,
    monthlyPrice: 2299,
    featured: true,
  },
  {
    id: 3,
    name: "Iron Arena Dwaraka Nagar",
    address: "Dwaraka Nagar, Visakhapatnam",
    lat: 17.74,
    lng: 83.313,
    rating: "4.6",
    hourlyPrice: 89,
    weeklyPrice: 549,
    monthlyPrice: 1899,
    featured: false,
  },
  {
    id: 4,
    name: "Beachside Fitness Seethammadhara",
    address: "Seethammadhara, Visakhapatnam",
    lat: 17.728,
    lng: 83.297,
    rating: "4.4",
    hourlyPrice: 69,
    weeklyPrice: 449,
    monthlyPrice: 1499,
    featured: true,
  },
  {
    id: 5,
    name: "Gajuwaka Fitness Hub",
    address: "Gajuwaka, Visakhapatnam",
    lat: 17.699,
    lng: 83.234,
    rating: "4.3",
    hourlyPrice: 59,
    weeklyPrice: 399,
    monthlyPrice: 1299,
    featured: false,
  },
  {
    id: 6,
    name: "Elite Gym Daba Gardens",
    address: "Daba Gardens, Visakhapatnam",
    lat: 17.726,
    lng: 83.308,
    rating: "4.9",
    hourlyPrice: 129,
    weeklyPrice: 799,
    monthlyPrice: 2599,
    featured: true,
  },
  {
    id: 7,
    name: "Active Life Maharanipeta",
    address: "Maharanipeta, Visakhapatnam",
    lat: 17.718,
    lng: 83.298,
    rating: "4.5",
    hourlyPrice: 89,
    weeklyPrice: 549,
    monthlyPrice: 1799,
    featured: false,
  },
  {
    id: 8,
    name: "NAD Fitness Center",
    address: "NAD Kotha Road, Visakhapatnam",
    lat: 17.71,
    lng: 83.285,
    rating: "4.2",
    hourlyPrice: 69,
    weeklyPrice: 429,
    monthlyPrice: 1399,
    featured: false,
  },
  {
    id: 9,
    name: "Simhachalam Health Club",
    address: "Simhachalam, Visakhapatnam",
    lat: 17.782,
    lng: 83.248,
    rating: "4.6",
    hourlyPrice: 79,
    weeklyPrice: 499,
    monthlyPrice: 1599,
    featured: false,
  },
  {
    id: 10,
    name: "Madhurawada Fit Zone",
    address: "Madhurawada, Visakhapatnam",
    lat: 17.752,
    lng: 83.342,
    rating: "4.7",
    hourlyPrice: 99,
    weeklyPrice: 599,
    monthlyPrice: 1999,
    featured: true,
  },
  {
    id: 11,
    name: "Lawsons Bay Gym",
    address: "Lawsons Bay Colony, Visakhapatnam",
    lat: 17.738,
    lng: 83.335,
    rating: "4.8",
    hourlyPrice: 109,
    weeklyPrice: 649,
    monthlyPrice: 2199,
    featured: true,
  },
];

export async function GET() {
  return NextResponse.json(gyms);
}
